### ISSUE TITLE
为什么预测结果的热图无法生成呢？

### ISSUE THREAD

**Issue by dai199478** [uestcchicken/MCNN#2]
我在调用 python test.py B(A) 的时候，
在 network.py 的 test 函数中，加入了heatmap 函数的调用，如下：
```Python
                x_in = np.reshape(d[0], (1, d[0].shape[0], d[0].shape[1], 1))
                y_p_den = sess.run(self.y_pre, feed_dict = {self.x: x_in})
                
                y_p = np.sum(y_p_den)
                heatmap(y_p_den, i, self.dataset, 'pre')
```
结果在这一行代码中出错了：
```Python
den_resized[i][j] = den[0][int(i / 4)][int(j / 4)]
```
整体代码如下：
```Python

    if info == 'pre':
        den_resized = np.zeros((den.shape[0] * 4, den.shape[1] * 4))
        for i in range(den_resized.shape[0]):
            for j in range(den_resized.shape[1]):
                den_resized[i][j] = den[0][int(i / 4)][int(j / 4)]
        den = den_resized
```

结果报如下错误：
```Python
generating heat map for img 1
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    mcnn.test()
  File "C:\Users\Creator\Desktop\MCNN-master\network.py", line 239, in test
    heatmap(y_p_den, i, self.dataset, 'pre')
  File "C:\Users\Creator\Desktop\MCNN-master\heatmap.py", line 41, in heatmap
    den_resized[i][j] = den[int(i / 4)][int(j / 4)] / 16
ValueError: setting an array element with a sequence.
```
求解答
@uestcchicken

**Comment by uestcchicken** [comment]
@dai199478 这是因为网络跑出来的y_p_den的形状是1x高x宽x1，在调用heatmap前加一句reshape就可以了
``
y_p_den = np.reshape(y_p_den, (y_p_den.shape[1], y_p_den.shape[2]))
``
（热力图一块只是想让结果可视化一下，没注意细节bug比较多）

**Comment by dai199478** [comment]
非常感谢你的回复，我已经解决了，对numpy不熟。。。
